package com.blog.BlogApp.Dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
public class CategoryDto {

    private Long categoryId;
    
    
    @Size(min = 5, max=10, message="Category Name should be between 5 and 10 words")
    private String categoryName;
    
    
    @Size(min = 10, max=50, message="Category description should be between 10 and 50 words")
    private String categoryDescription;

    // Constructors, getters, and setters are automatically generated by Lombok.
}
